@DataServing_HostAddress = http://localhost:5115

GET {{DataServing_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{DataServing_HostAddress}}/api/Analyze/categories?domain=x.com
Accept:application/json

###

GET {{DataServing_HostAddress}}/api/Analyze/dashboard?domain=x.com
Accept:application/json

###

GET {{DataServing_HostAddress}}/api/Analyze/authors?domain=x.com
Accept:application/json

###

GET {{DataServing_HostAddress}}/api/Analyze/date?domain=x.com&date=2024-03-02
Accept:application/json

###

GET {{DataServing_HostAddress}}/api/Analyze/countries?domain=x.com&date=2024-03-02
Accept:application/json

###

GET {{DataServing_HostAddress}}/api/Article/trending?domain=example.com&ip=102.129.65.0
Accept:application/json


###

GET {{DataServing_HostAddress}}/api/Article/recommended?domain=example.com&userId=3
Accept:application/json

###

GET {{DataServing_HostAddress}}/api/Analyze/posttypes?domain=www.almayadeen.net&date_from=2024-03-30&date_to=2024-04-26
Accept:application/json

###

GET {{DataServing_HostAddress}}/api/Analyze/tags?domain=www.almayadeen.net&date_from=2024-03-30&date_to=2024-04-26&posttype=
Accept:application/json