@DataServing_HostAddress = http://localhost:5115

GET {{DataServing_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{DataServing_HostAddress}}/api/Analyze/categories?domain=x.com
Accept:application/json

###

GET {{DataServing_HostAddress}}/api/Analyze/dashboard?domain=x.com
Accept:application/json

###

GET {{DataServing_HostAddress}}/api/Analyze/authors?domain=x.com
Accept:application/json

###

GET {{DataServing_HostAddress}}/api/Analyze/date?domain=x.com&date=2024-03-02
Accept:application/json

###

GET {{DataServing_HostAddress}}/api/Analyze/location?domain=x.com&date=2024-03-02
Accept:application/json